### PR TITLE
[issue 12] use static casts to mwSize

### PR DESCRIPTION
**Pull request by jgrewe**
... this does the job for me right now, but see #12

### CODE REVIEW

**Comment by gicmo** [comment]
TBH, not a huge fan of that change, because I'd be interested in fixing the real issue not the symptom. Bug I guess better then not compiling right now. Can we at least open an issue (in nix maybe?) and mark these lins as band-aids?

**Comment by jgrewe** [comment]
sure, I agree, don't like it myself. What do you mean with mark as band-aids? Something like "FIXME"s in the code?

**Comment by asobolev** [comment]
IMHO these xxxCount can be just removed.

If we have all children objects as (dependent) properties then the size will be shown when displayed and getting it is as easy as 

size(f.blocks)

or similar for other objects.

**Comment by gicmo** [comment]
Yeah, let's just remove these xxxCount functions everywhere!

**Comment by jgrewe** [comment]
ok, great, I will just close this one and someone else may delete the methods

**Pull request closed without merging**
