### PR TITLE
Add group entity

### PR DESCRIPTION
**Pull request by mpsonntag**
- Added bindings for the new nix.Group entity
- Added tests for all implemented features.
- All implemented features are successfully tested under win32 and win64.

### CODE REVIEW

**Comment by gicmo** [comment]
Runs on OSX with R2013b too.

**Comment by jgrewe** [comment]
@gicmo, do you miss something here, or is it ready for merging?

**Comment by gicmo** [comment]
@jgrewe linux tests ;)

**Comment by jgrewe** [comment]
Runs on ubuntu 14.04 with Matlab R2015b.

We need to include linux guidelines into readme. This includes setting the libstd link and in my case ignoring the hdf5 mismatch...

**Comment by jgrewe** [comment]
hang on, something went wrong on ubuntu side... need to re-check

**Comment by gicmo** [comment]
Since the Linux build & running issues are a thing of their one I merged this.

**Pull request merged**
